/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("Test Passed!!!");
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
